# docker-compose.yml
services:
  web:
    build: .
    command: ["gunicorn", "core.wsgi:application", "--bind", "0.0.0.0:${PORT}"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # optional for local testing
    env_file:
      - .env
    restart: unless-stopped
